sudo: false
language: node_js
node_js:
- '0.12'
- '4'
- '5'
- '6'
after_success: npm run coveralls
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: VWv3foE2BRlden53uDeS7zJ4RW9JQiOZIrazqqXKM+5GGPmCbhOdaC73U6NVNchNiDKYbESN3rigNIkGfBSfCoGSXHq3CC978QuFDoWCkqF5UpYRPsZ6tP7eLHi5IBYH98+0NgmZrc3kipb6cHarrGaWFwULkc4201kLdG6o8VpogcP+eQGBrr07HosC9cqBNIwvVwzWOCEhv03VTarIwuQHcxQzuQ/pTYJa1O8xU3WTVO3tJ1tnQdpDSNu65akucGlVMz1KKDaH3TLoAPck9tnQKk6UmHrh5mC6zzrpph6aofr0MTBp/UQgqODCRV8N/rQhvcoVPXee6JbcHx3IhlqAEQK5gaibQvFyUzh7/1RcdShy2NXoVlGVjvU1yt7QfXqLzPAcWydizTn+pOmLvai30Q/JWSA+BDG5FCv1gBN8CJ+NaYdUcFqWwujIF17rE+k8jx9qJb6Q0Qow+rYBdzWgfLoTGNzpfY8HkiKOrQ/iTsDjdhMtLB8wULHLNTLBRr/Jd/GCZRzMU37MnWP9GryJGFhP8vdT32ZPnT0m8OOEn3d0d9P5LaXmxJdx9wSj2wU8H9A47h2zzzjO2YTGfQpGabh7lwRysBwZkareCjfgUIBrOF5o9e47Ar4s2EX4OZ8+IJ2XmILDTF0zyNQSBcre9cnisvkicBERayYuPp8=
  on:
    tags: true
