sudo: false
language: node_js
node_js:
- '5'
- '4'
- '0.12'
services:
- docker
before_install:
- docker-compose up -d
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: oGjQL3wutktwJimq4xcwRep1cJBs3cSi5MHTHV1YMhNoeWrs5cnC1ynrDLW1I5I7oOI15uYIb4OimigbGFg3T3DvCAhLr7s6CD4CUOg02KiL/zehBRkBZxQdiZUtV+Owg4GPx3CTTzXk6Mg8RM7h5bAe1e77aJ/xw0L8KOY91YWZaUTWhxZUcjow3LAbp3vOgzLgfs1MBkX+HVdkgWLXl3Jz5dWnhUBzAzppQE2z9ZH5o/j/xjp4yhYJTE9BXMYcg5L407stzgb4FR0EtLfvXbA4kLHXJZLnrtVboVPhev0DThPFHDqyJgDuoRKYMlVXhBVD2aYClDpE30K3hjk6v1F9X/dU0SpwvtJ+HHMffUDwiafxlCIhXyq2CtYvmAMOrd5Y4d3eMm+57i3bHM3ZD4DoWJSr9wOG+Y6tNWWfVnMuDbEuw1algIRnNaGaSKkU5OBemmJlqMlQvIShrSJW+zVK0BUWxuGRX+6N/0LghUTnz0Cbsfx59zFuSpg/NJ1EUsxF03iKu38c3A9CnALjP40eRTAaHobu812VWZlBYaph5ExzYav1NWOMaTC+6IQNOjv0PC+mG1ZhvIUIZJWDEBnMKrTiNIG3Nd7v6/IkMEfEScSQH+XEnpJlVLXkcKAer/tg1ilIzqc0S+Dze5z+lYuVCOSUxLCwZZGuYtzW4jc=
  on:
    tags: true
