sudo: false
language: node_js
node_js:
- '5'
- '4'
- '0.12'
services:
- docker
before_install:
- docker-compose up -d
deploy:
  provider: npm
  email: dev@coorpacademy.com
  api_key:
    secure: GJwizDjDmuJMd7YfZjuOeDj8eWJo4DOgHpROPxMhsDaW30dF3AQ/2QtFJDoLtqu9kpYLSoFf+xk5PaVMBJMGHPag1JCCsLcoBJrjTuGoJa985jbSyM4MWY5aNN29bJWG8Mq+eJrO0TyV/xjKsip5ZWpQu41Aes+vHcam5qkw55SG1sp0BQQFC1ZIxvA1RhvWU8aCj4K2BL3dZhV1ANFOmIGgD+kmtTWIfvRAvL216AR/zzFDPfCMntrcRB7oJiHMZjMA97kwP3MlGa/BfbIdLaCDihWnpSmeKZe5afH7aYfYngCZEndJNSoJevXWfUp27eL+3qVVuh2Axj2oZjZrspP1j57ow5eCYBxfgTBxOiA6SvaVrLUlh4YcLqH+VwqkytyccVDE23YCnCLCCMOpddQIynCWhO53FV+sexqt5Xc0T/mrhpAkljoGHbCZjKHfj5EEW19iAZ17DyjNP/INSXy3NndzdLphyOHdInWU1ZX91cyOpq/KRDV0VXkDt64JGwdaziHsbSpRQt5g2Fv8cyL3xl8GZUzHIQ1kcMEPr+oU52AQub4ndGjgDUmYxZ4JgYBY1QdmU7eu4P66NSRvcW32UGkBPHjCMDlRBsAhNB0Oy6yCvVo+u2SL5bLGv/acPMSAcuj3ordrZ430uNqguDfnAu5qHMcVNn3mfr0uu2k=
  on:
    tags: true
