etcd:
  image: quay.io/coreos/etcd
  ports:
    - "4001:4001"
  command: -listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' -advertise-client-urls http://localhost:2379,http://localhost:4001
